### ISSUE TITLE
MemoryError on Ubuntu with small query

### ISSUE THREAD

**Issue by samuelcolvin** [JuliaDB/ODBC.jl#49] opened 2014-05-21 01:17 UTC
When I try to connect to a large MySQL db, but doing a small query on a small table I get a MemoryError:

	julia> Pkg.add("ODBC")
	julia> using ODBC
	julia> conn=ODBC.connect("markets")
	ODBC Connection Object
	----------------------
	Connection Data Source: markets
	markets Connection Number: 1
	Contains resultset? No
	julia> df=query("select * from markets_trace limit 1")
	elapsed time: 0.042409949 seconds
	1x7 DataFrame
	|-------|-------------|-------------|---------|
	| Col # | Name        | Eltype      | Missing |
	| 1     | id          | Int32       | 0       |
	| 2     | name        | UTF16String | 0       |
	| 3     | description | UTF16String | 0       |
	| 4     | code        | UTF16String | 0       |
	| 5     | exchange_id | Int32       | 0       |
	| 6     | type_id     | Int32       | 0       |
	| 7     | testing     | Int8        | 0       |
	julia> df=query("select * from markets_trace limit 5")
	ERROR: MemoryError()
	 in ODBCColumnAllocate at /home/samuel/.julia/v0.3/ODBC/src/backend.jl:107
	 in ODBCBindCols at /home/samuel/.julia/v0.3/ODBC/src/backend.jl:90
	 in query at /home/samuel/.julia/v0.3/ODBC/src/userfacing.jl:54
	 in query at /home/samuel/.julia/v0.3/ODBC/src/userfacing.jl:43

The first query with `limit 1` uses up 8gb of ram, the second even with that memory freed always crashes.

Calling the query from the prompt returned by `sqli markets` is absolutely fine.

System Details:

    Ubuntu: 14.04 64bit
    unixodbc: 2.2.14p2-5ubuntu5
    libmyodbc: 5.1.10-3
    julia: latest

**Comment by quinnj** [comment] 2016-05-03 18:49
duplicate of #53

**Closed by quinnj** 2016-05-03 18:49 UTC
