### ISSUE TITLE
querying a LONGBLOB or LONGTEXT causes ERROR: MemoryError()

### ISSUE THREAD

**Issue by martinmev** [JuliaDB/ODBC.jl#83] opened 2015-05-08 21:36 UTC
julia> query("select data from users")
ERROR: MemoryError()
in ODBCColumnAllocate at /root/.julia/v0.3/ODBC/src/backend.jl:112
in ODBCBindCols at /root/.julia/v0.3/ODBC/src/backend.jl:95
in query at /root/.julia/v0.3/ODBC/src/userfacing.jl:53
in query at /root/.julia/v0.3/ODBC/src/userfacing.jl:42

The column 'data'  has type 'longtext' (the maximal text size is 451 bytes in the column 'data'). ODBCColumnAllocate tries to allocate 4 GB (the size of the type longtext).

Possible solutions:

a) Error message "LONGBLOB and LONGTEXT types are not supported." if type size > 16777215 (mediumtext).

b) To retrieve all columns via the method SQLGetData instead of binding columns (SQLBindCol).
(Getting Long Data: https://msdn.microsoft.com/en-us/library/ms712426%28v=vs.85%29.aspx).

Julia version 0.3.7 (Linux, unixodbc), 0.3.6 (Windows 7 64bit)
ODBC.jl version 0.3.10
Database: MySQL

**Comment by quinnj** [comment] 2016-05-03 18:49
Duplicate of #53

**Closed by quinnj** 2016-05-03 18:49 UTC
